import { Test } from '../types';

// Most static data is now removed as content is generated by the Gemini API.
// The placement test is kept as a static entry point to determine the user's initial level.

export const placementTest: Test = {
    mcqs: [
        { question: 'A brother or sister', options: ['cousin', 'relative', 'parent', 'sibling'], correctAnswer: 'sibling' },
        { question: 'A set of instructions for cooking a dish', options: ['ingredient', 'nutrition', 'recipe', 'beverage'], correctAnswer: 'recipe' },
        { question: 'Featuring new methods; advanced and original', options: ['digital', 'convenient', 'innovative', 'sustainable'], correctAnswer: 'innovative' },
        { question: 'To protect something from harm or destruction', options: ['recycle', 'pollute', 'conserve', 'destroy'], correctAnswer: 'conserve' },
    ],
    fillInTheBlanks: [
        { sentence: 'A smartphone is a very useful ___.', correctAnswer: 'device' },
        { sentence: 'Good ___ is essential for growing children.', correctAnswer: 'nutrition' },
        { sentence: 'The destruction of forests is destroying the ___ of many species.', correctAnswer: 'habitat' },
    ],
    matchingPairs: [], // Placement test can be simpler
};

export const speakingTestData = (topic: string) => ({
    part1: [
        "Let's talk about your hometown. Can you describe it for me?",
        `What do you like most about your hometown?`,
        `Now, let's move on to talk about ${topic}. Do you think ${topic} is important?`,
        `How has ${topic} changed in your country in recent years?`,
    ],
    part2: [
        `Describe an experience you had related to ${topic}.
        You should say:
        - what the experience was
        - when and where it happened
        - who you were with
        and explain how you felt about this experience.`
    ],
    part3: [
        `What are the general attitudes of people in your country towards ${topic}?`,
        `How do you think technology will affect ${topic} in the future?`,
        `What are the pros and cons of international cooperation on issues related to ${topic}?`,
    ]
});