import { Test } from '../types';

// Most static data is now removed as content is generated by the Gemini API.
// The placement test is kept as a static entry point to determine the user's initial level.

export const placementTest: Test = {
    mcqs: [
        { question: 'A brother or sister', options: ['cousin', 'relative', 'parent', 'sibling'], correctAnswer: 'sibling' },
        { question: 'A set of instructions for cooking a dish', options: ['ingredient', 'nutrition', 'recipe', 'beverage'], correctAnswer: 'recipe' },
        { question: 'Featuring new methods; advanced and original', options: ['digital', 'convenient', 'innovative', 'sustainable'], correctAnswer: 'innovative' },
        { question: 'To protect something from harm or destruction', options: ['recycle', 'pollute', 'conserve', 'destroy'], correctAnswer: 'conserve' },
    ],
    fillInTheBlanks: [
        { sentence: 'A smartphone is a very useful ___.', correctAnswer: 'device' },
        { sentence: 'Good ___ is essential for growing children.', correctAnswer: 'nutrition' },
        { sentence: 'The destruction of forests is destroying the ___ of many species.', correctAnswer: 'habitat' },
    ],
    matchingPairs: [], // Placement test can be simpler
};

export const speakingTestData = (topic: string) => ({
    part1: [
        "Let's talk about your hometown. Can you describe it for me?",
        `What do you like most about your hometown?`,
        `Now, let's move on to talk about daily routines. What is a typical day like for you?`,
        `How has your daily routine changed compared to when you were a child?`,
    ],
    part2: [
        `Now I'm going to give you a topic, and I'd like you to talk about it for one to two minutes.
        Before you talk, you'll have one minute to think about what you are going to say.
        You can make some notes if you wish.
        
        Describe the image you see.
        You should say:
        - what is happening in the image
        - what the main objects or people are
        - what kind of atmosphere or mood the image creates
        and explain what this image makes you think about.`
    ],
    part3: [
        `Let's discuss this further. How important is visual information in today's world?`,
        `Do you think AI-generated images can be considered art? Why or why not?`,
        `What are the potential benefits and drawbacks of being able to create any image from a text description?`,
    ]
});